"""Master Schema v1

Revision ID: 7761552518e7
Revises: 
Create Date: 2025-12-17 18:02:40.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7761552518e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiendas',
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('config_pagos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_zonas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tienda_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tienda_id', 'telegram_user_id', name='unique_tienda_customer')
    )
    op.create_table('productos',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tiene_variantes', sa.Boolean(), nullable=True),
    sa.Column('tipo_producto', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('producto_id')
    )
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('response_received', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_memory',
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('zona_preferida', sa.String(length=100), nullable=True),
    sa.Column('preferencias_producto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tono_detectado', sa.String(length=50), nullable=True),
    sa.Column('intencion_compra', sa.String(length=100), nullable=True),
    sa.Column('dolor_principal', sa.Text(), nullable=True),
    sa.Column('ultima_objecion', sa.Text(), nullable=True),
    sa.Column('resumen_conversacion', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantes',
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('nombre_variante', sa.String(length=100), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('precio_ajuste', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variante_id')
    )
    op.create_table('ordenes',
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('monto_subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('zona_entrega', sa.String(length=100), nullable=True),
    sa.Column('direccion_entrega', sa.Text(), nullable=True),
    sa.Column('fecha_entrega_programada', sa.Date(), nullable=True),
    sa.Column('external_payment_id', sa.String(length=100), nullable=True),
    sa.Column('comprobante_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ),
    sa.PrimaryKeyConstraint('orden_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.tienda_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_orden',
    sa.Column('detalle_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.orden_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.variante_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.variante_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_items')
    op.drop_table('detalles_orden')
    op.drop_table('quotes')
    op.drop_table('ordenes')
    op.drop_table('variantes')
    op.drop_table('opportunities')
    op.drop_table('customer_memory')
    op.drop_table('ai_interactions')
    op.drop_table('productos')
    op.drop_table('customers')
    op.drop_table('tiendas')
    # ### end Alembic commands ###
